import jsPDF from 'jspdf';
import { StartupIdea } from '../types';

export const generateMarketReportPDF = (idea: StartupIdea): void => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const lineHeight = 6;
    let yPosition = margin;

    // Helper function to add text with word wrapping
    const addWrappedText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 12): number => {
      doc.setFontSize(fontSize);
      const lines = doc.splitTextToSize(text, maxWidth);
      doc.text(lines, x, y);
      return y + (lines.length * lineHeight);
    };

    // Helper function to check if we need a new page
    const checkNewPage = (requiredSpace: number): number => {
      if (yPosition + requiredSpace > pageHeight - margin) {
        doc.addPage();
        return margin;
      }
      return yPosition;
    };

    // Header with company branding
    doc.setFillColor(147, 51, 234); // Purple color
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('SkillHatch', margin, 25);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Deep Market Analysis Report', margin, 35);

    yPosition = 60;
    doc.setTextColor(0, 0, 0);

    // Title Section
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    yPosition = addWrappedText(idea.title, margin, yPosition, pageWidth - 2 * margin, 18);
    yPosition += 15;

    // Executive Summary
    yPosition = checkNewPage(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Executive Summary', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    yPosition = addWrappedText(idea.description, margin, yPosition, pageWidth - 2 * margin, 10);
    yPosition += 15;

    // Market Overview
    yPosition = checkNewPage(40);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Market Overview', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const marketAnalysis = `Market Size: ${idea.marketSize}

Target Market: ${idea.targetAudience}

Revenue Model: ${idea.revenueModel}

Time to Market: ${idea.timeToMarket}

Difficulty Level: ${idea.difficulty}

Competitive Advantage: ${idea.competitiveAdvantage}

Key Features:
${idea.keyFeatures.map(feature => `• ${feature}`).join('\n')}

Market Analysis:
This startup idea represents a significant opportunity in the current market landscape. The target audience shows strong demand for innovative solutions, and the competitive advantage provides a clear differentiation strategy.

Financial Projections:
Based on the ${idea.revenueModel.toLowerCase()} model, this venture shows promising revenue potential with manageable risk factors given the ${idea.difficulty.toLowerCase()} implementation complexity.

Risk Assessment:
• Market competition risks
• Technology implementation challenges  
• Customer acquisition costs
• Regulatory compliance requirements

Success Factors:
• Strong product-market fit
• Effective marketing strategy
• Operational excellence
• Strategic partnerships

Recommendations:
1. Validate market demand through customer interviews
2. Develop MVP with core features
3. Establish key partnerships early
4. Focus on customer acquisition and retention
5. Monitor key performance indicators closely`;

    yPosition = addWrappedText(marketAnalysis, margin, yPosition, pageWidth - 2 * margin, 10);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated by SkillHatch - ${new Date().toLocaleDateString()}`, margin, pageHeight - 10);
    doc.text(`Confidential Market Analysis`, pageWidth - margin - 60, pageHeight - 10);

    // Save the PDF
    const fileName = `${idea.title.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')}_Market_Report.pdf`;
    doc.save(fileName);
    
    console.log('Market report PDF generated successfully');
  } catch (error) {
    console.error('Error generating market report PDF:', error);
    throw new Error('Failed to generate market report PDF');
  }
};

export const generateStartupToolkit = (idea: StartupIdea): void => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const lineHeight = 6;
    let yPosition = margin;

    // Helper function to add text with word wrapping
    const addWrappedText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 12): number => {
      doc.setFontSize(fontSize);
      const lines = doc.splitTextToSize(text, maxWidth);
      doc.text(lines, x, y);
      return y + (lines.length * lineHeight);
    };

    // Helper function to check if we need a new page
    const checkNewPage = (requiredSpace: number): number => {
      if (yPosition + requiredSpace > pageHeight - margin) {
        doc.addPage();
        return margin;
      }
      return yPosition;
    };

    // Header
    doc.setFillColor(147, 51, 234);
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('SkillHatch', margin, 25);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Startup Toolkit & Templates', margin, 35);

    yPosition = 60;
    doc.setTextColor(0, 0, 0);

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    yPosition = addWrappedText(`Startup Toolkit: ${idea.title}`, margin, yPosition, pageWidth - 2 * margin, 18);
    yPosition += 15;

    // Business Plan Template
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Business Plan Template', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const businessPlanContent = `1. Executive Summary
• Business concept: ${idea.description}
• Target market: ${idea.targetAudience}
• Competitive advantage: ${idea.competitiveAdvantage}
• Financial highlights and funding needs

2. Company Description
• Mission and vision statements
• Company history and ownership
• Legal structure and location

3. Market Analysis
• Industry overview and trends
• Market size: ${idea.marketSize}
• Competitive analysis and positioning

4. Products/Services
• Core features: ${idea.keyFeatures.join(', ')}
• Development timeline: ${idea.timeToMarket}
• Research and development activities

5. Marketing & Sales Strategy
• Revenue model: ${idea.revenueModel}
• Customer acquisition strategy
• Sales process and channels

6. Financial Projections
• 3-year revenue forecasts
• Break-even analysis
• Funding requirements and use of funds

7. Risk Analysis
• Market risks and mitigation strategies
• Operational and financial risks
• Contingency planning

8. Implementation Timeline
• Development phases and milestones
• Key performance indicators
• Success metrics and goals`;

    yPosition = addWrappedText(businessPlanContent, margin, yPosition, pageWidth - 2 * margin, 10);
    yPosition += 20;

    // Pitch Deck Template
    yPosition = checkNewPage(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Pitch Deck Template', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const pitchDeckContent = `Slide 1: Title Slide
• Company Name: ${idea.title}
• Tagline: [Your compelling one-liner]
• Presenter information

Slide 2: Problem Statement
• What problem are you solving?
• Market pain points
• Current solutions and limitations

Slide 3: Solution
• ${idea.description}
• Key benefits and value proposition
• Why now? Market timing

Slide 4: Market Opportunity
• Market size: ${idea.marketSize}
• Target audience: ${idea.targetAudience}
• Market trends and growth potential

Slide 5: Product Demo
• Core features: ${idea.keyFeatures.slice(0, 3).join(', ')}
• User experience walkthrough
• Product screenshots or mockups

Slide 6: Business Model
• Revenue model: ${idea.revenueModel}
• Pricing strategy
• Unit economics

Slide 7: Competitive Analysis
• Competitive landscape
• Your advantage: ${idea.competitiveAdvantage}
• Differentiation strategy

Slide 8: Go-to-Market Strategy
• Customer acquisition plan
• Marketing channels
• Sales strategy

Slide 9: Financial Projections
• Revenue forecasts
• Key metrics
• Funding requirements

Slide 10: Team
• Founder backgrounds
• Key team members
• Advisory board

Slide 11: Funding Ask
• Investment amount
• Use of funds
• Timeline and milestones

Slide 12: Contact Information
• Next steps
• Contact details
• Thank you`;

    yPosition = addWrappedText(pitchDeckContent, margin, yPosition, pageWidth - 2 * margin, 10);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated by SkillHatch - ${new Date().toLocaleDateString()}`, margin, pageHeight - 10);
    doc.text(`Startup Toolkit Templates`, pageWidth - margin - 50, pageHeight - 10);

    // Save the PDF
    const fileName = `${idea.title.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')}_Startup_Toolkit.pdf`;
    doc.save(fileName);
    
    console.log('Startup toolkit PDF generated successfully');
  } catch (error) {
    console.error('Error generating startup toolkit PDF:', error);
    throw new Error('Failed to generate startup toolkit PDF');
  }
};