/*
  # Seed Startup Ideas Data

  This migration populates the startup_ideas table with the existing startup templates
  from the frontend data file, converting them to the new database schema.
*/

-- Insert startup ideas data
INSERT INTO startup_ideas (
  title,
  description,
  market_size,
  difficulty,
  time_to_market,
  revenue_model,
  target_audience,
  key_features,
  competitive_advantage,
  required_skills,
  target_interests,
  keywords
) VALUES 
(
  'StudySync - Peer Learning Platform',
  'A platform connecting students for collaborative study sessions, note sharing, and peer tutoring with built-in scheduling and progress tracking.',
  '$8.2 billion (Online Tutoring Market)',
  'Medium',
  '4-6 months',
  'Freemium + Premium subscriptions',
  'College students, high school students, study groups',
  '["Virtual study rooms", "Note sharing marketplace", "Peer matching algorithm", "Progress tracking", "Integrated video chat"]'::jsonb,
  'Student-to-student focus with gamified learning and affordable pricing',
  '["Web Development", "Mobile Development", "Design"]'::jsonb,
  '["Education", "Technology", "Social Media"]'::jsonb,
  '["study", "learning", "education", "student", "peer", "tutoring"]'::jsonb
),
(
  'CampusEats - Student Food Network',
  'A hyperlocal food delivery service connecting students with campus dining options, local restaurants, and student-run food businesses.',
  '$4.3 billion (Campus Food Services)',
  'Medium',
  '3-5 months',
  'Commission + Delivery fees',
  'College students, campus dining services, local restaurants',
  '["Campus-specific delivery zones", "Student discount integration", "Group ordering for dorms", "Meal plan integration", "Student chef marketplace"]'::jsonb,
  'Deep campus integration and student-friendly pricing with flexible payment options',
  '["Mobile Development", "Web Development", "Business"]'::jsonb,
  '["Food", "Business", "Community"]'::jsonb,
  '["food", "delivery", "campus", "student", "restaurant", "dining"]'::jsonb
),
(
  'SkillSwap - Student Freelance Hub',
  'A marketplace where students can offer their skills (design, coding, writing, tutoring) to other students and small businesses at affordable rates.',
  '$1.27 billion (Student Services Market)',
  'Easy',
  '2-4 months',
  'Commission + Featured listings',
  'Students seeking income, small businesses, other students',
  '["Skill verification system", "Student-friendly pricing", "Portfolio showcase", "Secure payment processing", "Rating and review system"]'::jsonb,
  'Student-focused with lower fees and educational project emphasis',
  '["Web Development", "Design", "Marketing"]'::jsonb,
  '["Business", "Freelancing", "Skills Development"]'::jsonb,
  '["freelance", "skills", "marketplace", "student", "gig", "services"]'::jsonb
),
(
  'EcoTrack - Campus Sustainability Tracker',
  'An app that helps students track their environmental impact on campus, find sustainable options, and participate in eco-friendly challenges.',
  '$2.8 billion (Environmental Apps Market)',
  'Easy',
  '3-5 months',
  'Freemium + Partnerships with eco-brands',
  'Environmentally conscious students, campus sustainability offices',
  '["Carbon footprint tracking", "Sustainable dining options", "Eco-challenge leaderboards", "Recycling location finder", "Green transportation tracker"]'::jsonb,
  'Campus-specific data and integration with university sustainability programs',
  '["Mobile Development", "Data Science", "Design"]'::jsonb,
  '["Environment", "Sustainability", "Health"]'::jsonb,
  '["environment", "sustainability", "green", "eco", "campus", "carbon"]'::jsonb
),
(
  'BudgetBuddy - Student Finance Manager',
  'A simple, student-focused budgeting app that helps track expenses, manage student loans, and find money-saving opportunities on campus.',
  '$1.57 billion (Personal Finance Apps)',
  'Easy',
  '2-3 months',
  'Freemium + Affiliate partnerships',
  'College students, recent graduates, young adults',
  '["Student loan tracking", "Campus discount finder", "Textbook cost optimizer", "Expense categorization", "Savings goal setting"]'::jsonb,
  'Specifically designed for student financial challenges and campus life',
  '["Mobile Development", "Finance", "Data Science"]'::jsonb,
  '["Finance", "Technology", "Student Life"]'::jsonb,
  '["budget", "finance", "money", "student", "savings", "expenses"]'::jsonb
),
(
  'EventHub - Campus Social Network',
  'A platform for discovering, creating, and managing campus events, from study groups to social gatherings, with integrated RSVP and networking features.',
  '$1.1 billion (Event Management Software)',
  'Medium',
  '4-6 months',
  'Freemium + Event promotion fees',
  'College students, student organizations, campus event organizers',
  '["Event discovery feed", "RSVP management", "Student organization profiles", "Campus calendar integration", "Social networking features"]'::jsonb,
  'Campus-specific with student organization integration and academic calendar sync',
  '["Web Development", "Social Media", "Design"]'::jsonb,
  '["Social Media", "Events", "Community"]'::jsonb,
  '["events", "campus", "social", "networking", "student", "activities"]'::jsonb
),
(
  'DormSwap - Student Marketplace',
  'A peer-to-peer marketplace for students to buy, sell, and trade textbooks, furniture, electronics, and other college essentials.',
  '$890 million (Student Marketplace)',
  'Easy',
  '2-4 months',
  'Commission + Featured listings',
  'College students, dormitory residents, graduating students',
  '["Textbook price comparison", "Dorm-specific listings", "Semester-end bulk sales", "Student verification system", "Local pickup coordination"]'::jsonb,
  'Student-verified community with campus-specific logistics and academic calendar integration',
  '["E-commerce", "Mobile Development", "Design"]'::jsonb,
  '["Business", "Student Life", "Sustainability"]'::jsonb,
  '["marketplace", "textbooks", "dorm", "student", "buy", "sell"]'::jsonb
),
(
  'MindSpace - Student Wellness Companion',
  'A mental health app designed specifically for students, offering stress management tools, study break reminders, and peer support networks.',
  '$3.9 billion (Mental Health Apps)',
  'Medium',
  '4-7 months',
  'Freemium + University partnerships',
  'College students, university counseling centers, student wellness programs',
  '["Stress level tracking", "Study break reminders", "Anonymous peer support", "Campus counseling integration", "Exam anxiety management"]'::jsonb,
  'Student-specific stressors focus with campus counseling service integration',
  '["Mobile Development", "Psychology", "Healthcare"]'::jsonb,
  '["Mental Health", "Healthcare", "Student Life"]'::jsonb,
  '["mental", "health", "wellness", "stress", "student", "anxiety"]'::jsonb
),
(
  'LearnLab - Micro-Learning Platform',
  'A platform offering bite-sized skill courses taught by students and young professionals, focusing on practical skills for career development.',
  '$5.2 billion (Online Learning Market)',
  'Medium',
  '5-8 months',
  'Course sales + Subscription tiers',
  'Students, young professionals, career changers',
  '["15-minute skill modules", "Student instructor program", "Career path recommendations", "Skill verification badges", "Peer learning groups"]'::jsonb,
  'Student-taught practical skills with affordable pricing and career-focused content',
  '["Web Development", "Education", "Video Production"]'::jsonb,
  '["Education", "Skills Development", "Career"]'::jsonb,
  '["learning", "skills", "courses", "career", "education", "training"]'::jsonb
),
(
  'CampusRide - Student Transportation Network',
  'A ride-sharing platform specifically for students, connecting those who need rides with student drivers for campus, airport, and city trips.',
  '$2.1 billion (Campus Transportation)',
  'Medium',
  '4-6 months',
  'Commission + Premium features',
  'College students, commuter students, student drivers',
  '["Student verification system", "Campus route optimization", "Split fare calculations", "Safety features and tracking", "Recurring trip scheduling"]'::jsonb,
  'Student-only community with campus-specific routes and affordable pricing',
  '["Mobile Development", "Logistics", "Safety"]'::jsonb,
  '["Transportation", "Community", "Business"]'::jsonb,
  '["ride", "sharing", "transportation", "campus", "student", "carpool"]'::jsonb
),
(
  'FitMate - Student Fitness Accountability',
  'A fitness app that pairs students as workout buddies, tracks gym usage, and creates fitness challenges tailored to busy student schedules.',
  '$1.8 billion (Fitness Apps)',
  'Easy',
  '3-5 months',
  'Freemium + Campus gym partnerships',
  'College students, campus recreation centers, fitness enthusiasts',
  '["Workout buddy matching", "Campus gym integration", "Quick workout routines", "Study break fitness reminders", "Student fitness challenges"]'::jsonb,
  'Student schedule-aware with campus gym integration and peer accountability focus',
  '["Mobile Development", "Health", "Social Media"]'::jsonb,
  '["Fitness", "Health", "Social Media"]'::jsonb,
  '["fitness", "workout", "gym", "health", "student", "exercise"]'::jsonb
),
(
  'StudentSaver - Local Discount Network',
  'An app connecting students with local businesses offering student discounts, deals, and part-time job opportunities in their area.',
  '$1.4 billion (Local Business Apps)',
  'Easy',
  '2-4 months',
  'Commission + Business listing fees',
  'College students, local businesses, student job seekers',
  '["Student ID verification", "Location-based deals", "Part-time job board", "Business review system", "Deal notification alerts"]'::jsonb,
  'Hyper-local focus with verified student discounts and integrated job opportunities',
  '["Mobile Development", "Business", "Marketing"]'::jsonb,
  '["Business", "Local Community", "Savings"]'::jsonb,
  '["discounts", "deals", "local", "business", "student", "savings"]'::jsonb
),
(
  'GradMap – Career Planning Companion',
  'An app that helps students explore career paths, align courses with goals, build resumes, and connect with alumni mentors.',
  '$6.4 billion (Career Development Market)',
  'Medium',
  '4-6 months',
  'Freemium + Career services partnerships',
  'College students, recent graduates, career counselors',
  '["Career goal roadmap", "Resume builder", "Alumni mentor matching", "Job/internship integration", "Skill gap analysis"]'::jsonb,
  'Integrated academic and career planning with peer-alumni mentorship',
  '["Web Development", "Career Counseling", "Design"]'::jsonb,
  '["Career", "Education", "Mentorship"]'::jsonb,
  '["career", "resume", "student", "mentor", "goals", "internship"]'::jsonb
),
(
  'RoomiLink – Smart Roommate Matcher',
  'An AI-powered platform for matching students with compatible roommates based on preferences, habits, and schedules.',
  '$1.3 billion (Student Housing Services)',
  'Medium',
  '3-5 months',
  'Freemium + Premium matchmaking',
  'College students, student housing providers',
  '["Compatibility quiz", "Conflict resolution tips", "Housing preference filters", "Chat and connect", "Lease splitting options"]'::jsonb,
  'AI-driven compatibility matching with integrated housing support',
  '["Mobile Development", "AI/ML", "UX Design"]'::jsonb,
  '["Housing", "Lifestyle", "AI"]'::jsonb,
  '["roommate", "housing", "student", "match", "dorm", "rental"]'::jsonb
),
(
  'NoteNexus – AI-Powered Class Notes Generator',
  'An AI tool that generates class notes, summaries, and flashcards from uploaded lectures, PDFs, and handwritten content.',
  '$7.3 billion (EdTech Tools)',
  'Hard',
  '5-7 months',
  'Freemium + Premium tools + Institution licenses',
  'Students, educators, coaching centers',
  '["AI lecture transcription", "Handwriting recognition", "Auto-summary generator", "Flashcard builder", "Multi-language support"]'::jsonb,
  'Combines AI and OCR to serve students across various learning formats',
  '["AI/ML", "OCR/NLP", "Web Development"]'::jsonb,
  '["AI", "Education", "Productivity"]'::jsonb,
  '["notes", "AI", "OCR", "student", "flashcards", "summary"]'::jsonb
),
(
  'InternSync – Internship Discovery & Tracker',
  'A platform that aggregates internship listings, application deadlines, and tracks student applications with reminders and feedback tools.',
  '$2.6 billion (Internship Services)',
  'Easy',
  '2-3 months',
  'Freemium + Partner job board integration',
  'College students, placement cells, startups',
  '["Internship aggregator", "Deadline tracker", "Resume review tools", "Interview preparation kit", "Application calendar"]'::jsonb,
  'Simplifies internship search and tracking in one place',
  '["Web Development", "Job Portal APIs", "UI Design"]'::jsonb,
  '["Career", "Productivity", "Jobs"]'::jsonb,
  '["internship", "student", "job", "career", "tracker", "resume"]'::jsonb
),
(
  'Thriftly – Campus Thrift Store App',
  'A digital thrift marketplace for students to buy, sell, and donate used clothes, accessories, and supplies within campus.',
  '$3.2 billion (Thrift & Secondhand Market)',
  'Easy',
  '2-4 months',
  'Transaction fee + Sustainability partnerships',
  'College students, eco-conscious youth',
  '["Sustainable fashion categories", "Donation tracking", "Campus delivery zones", "Rating system", "Eco-score calculator"]'::jsonb,
  'Sustainability-driven with campus-local delivery and verified listings',
  '["Mobile App", "Marketplace Management", "Design"]'::jsonb,
  '["Sustainability", "Fashion", "Student Life"]'::jsonb,
  '["thrift", "fashion", "student", "sustainable", "donate", "marketplace"]'::jsonb
);